<?php

namespace NumNum\UBL;

/**
 * All possible Payment Means Codes that can be used
 * To extend, see also: https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL4461/
 */
class UNCL4461
{
    const INSTRUMENT_NOT_DEFINED = "1";
    const AUTOMATED_CLEARING_HOUSE_CREDIT = "2";
    const AUTOMATED_CLEARING_HOUSE_DEBIT = "3";
    const ACH_DEMAND_DEBIT_REVERSAL = "4";
    const ACH_DEMAND_CREDIT_REVERSAL = "5";
    const ACH_DEMAND_CREDIT = "6";
    const ACH_DEMAND_DEBIT = "7";
    const HOLD = "8";
    const NATIONAL_OR_REGIONAL_CLEARING = "9";
    const IN_CASH = "10";
    const ACH_SAVINGS_CREDIT_REVERSAL = "11";
    const ACH_SAVINGS_DEBIT_REVERSAL = "12";
    const ACH_SAVINGS_CREDIT = "13";
    const ACH_SAVINGS_DEBIT = "14";
    const BOOKENTRY_CREDIT = "15";
    const BOOKENTRY_DEBIT = "16";
    const ACH_DEMAND_CASH_CONCENTRATION_OR_DISBURSEMENT_CREDIT = "17";
    const ACH_DEMAND_CASH_CONCENTRATION_OR_DISBURSEMENT_DEBIT = "18";
    const ACH_DEMAND_CORPORATE_TRADE_PAYMENT_CREDIT = "19";
    const CHEQUE = "20";
    const BANKERS_DRAFT = "21";
    const CERTIFIED_BANKERS_DRAFT = "22";
    const BANK_CHEQUE_ISSUED_BY_A_BANKING_OR_SIMILAR_ESTABLISHMENT = "23";
    const BILL_OF_EXCHANGE_AWAITING_ACCEPTANCE = "24";
    const CERTIFIED_CHEQUE = "25";
    const LOCAL_CHEQUE = "26";
    const ACH_DEMAND_CORPORATE_TRADE_PAYMENT_DEBIT = "27";
    const ACH_DEMAND_CORPORATE_TRADE_EXCHANGE_CREDIT = "28";
    const ACH_DEMAND_CORPORATE_TRADE_EXCHANGE_DEBIT = "29";
    const CREDIT_TRANSFER = "30";
    const DEBIT_TRANSFER = "31";
    const ACH_DEMAND_CASH_CONCENTRATION_OR_DISBURSEMENT_PLUS_CREDIT = "32";
    const ACH_DEMAND_CASH_CONCENTRATION_OR_DISBURSEMENT_PLUS_DEBIT = "33";
    const ACH_PREARRANGED_PAYMENT_AND_DEPOSIT = "34";
    const ACH_SAVINGS_CASH_CONCENTRATION_OR_DISBURSEMENT_CREDIT = "35";
    const ACH_SAVINGS_CASH_CONCENTRATION_OR_DISBURSEMENT_DEBIT = "36";
    const ACH_SAVINGS_CORPORATE_TRADE_PAYMENT_CREDIT = "37";
    const ACH_SAVINGS_CORPORATE_TRADE_PAYMENT_DEBIT = "38";
    const ACH_SAVINGS_CORPORATE_TRADE_EXCHANGE_CREDIT = "39";
    const ACH_SAVINGS_CORPORATE_TRADE_EXCHANGE_DEBIT = "40";
    const ACH_SAVINGS_CASH_CONCENTRATION_OR_DISBURSEMENT_PLUS_CREDIT = "41";
    const PAYMENT_TO_BANK_ACCOUNT = "42";
    const ACH_SAVINGS_CASH_CONCENTRATION_OR_DISBURSEMENT_PLUS_DEBIT = "43";
    const ACCEPTED_BILL_OF_EXCHANGE = "44";
    const REFERENCED_HOME_BANKING_CREDIT_TRANSFER = "45";
    const INTERBANK_DEBIT_TRANSFER = "46";
    const HOME_BANKING_DEBIT_TRANSFER = "47";
    const BANK_CARD = "48";
    const DIRECT_DEBIT = "49";
    const PAYMENT_BY_POSTGIRO = "50";
    const FR_NORME_6_97_TELEREGLEMENT_CFONB = "51";
    const URGENT_COMMERCIAL_PAYMENT = "52";
    const URGENT_TREASURY_PAYMENT = "53";
    const CREDIT_CARD = "54";
    const DEBIT_CARD = "55";
    const BANKGIRO = "56";
    const STANDING_AGREEMENT = "57";
    const SEPA_CREDIT_TRANSFER = "58";
    const SEPA_DIRECT_DEBIT = "59";
    const PROMISSORY_NOTE = "60";
    const PROMISSORY_NOTE_SIGNED_BY_THE_DEBTOR = "61";
    const PROMISSORY_NOTE_SIGNED_BY_THE_DEBTOR_AND_ENDORSED_BY_A_BANK = "62";
    const PROMISSORY_NOTE_SIGNED_BY_THE_DEBTOR_AND_ENDORSED_BY_A_THIRD_PARTY = "63";
    const PROMISSORY_NOTE_SIGNED_BY_A_BANK = "64";
    const PROMISSORY_NOTE_SIGNED_BY_A_BANK_AND_ENDORSED_BY_ANOTHER_BANK = "65";
    const PROMISSORY_NOTE_SIGNED_BY_A_THIRD_PARTY = "66";
    const PROMISSORY_NOTE_SIGNED_BY_A_THIRD_PARTY_AND_ENDORSED_BY_A_BANK = "67";
    const ONLINE_PAYMENT_SERVICE = "68";
    const BILL_DRAWN_BY_THE_CREDITOR_ON_THE_DEBTOR = "70";
    const BILL_DRAWN_BY_THE_CREDITOR_ON_A_BANK = "74";
    const BILL_DRAWN_BY_THE_CREDITOR_ENDORSED_BY_ANOTHER_BANK = "75";
    const BILL_DRAWN_BY_THE_CREDITOR_ON_A_BANK_AND_ENDORSED_BY_A_THIRD_PARTY = "76";
    const BILL_DRAWN_BY_THE_CREDITOR_ON_A_THIRD_PARTY = "77";
    const BILL_DRAWN_BY_CREDITOR_ON_THIRD_PARTY_ACCEPTED_AND_ENDORSED_BY_BANK = "78";
    const NOT_TRANSFERABLE_BANKERS_DRAFT = "91";
    const NOT_TRANSFERABLE_LOCAL_CHEQUE = "92";
    const REFERENCE_GIRO = "93";
    const URGENT_GIRO = "94";
    const FREE_FORMAT_GIRO = "95";
    const REQUESTED_METHOD_FOR_PAYMENT_WAS_NOT_USED = "96";
    const CLEARING_BETWEEN_PARTNERS = "97";
    const MUTUALLY_DEFINED = "ZZZ";
}
